Vagrant.configure("2") do |config|
    config.vm.define "scriptbox" do |scriptbox|    
      scriptbox.vm.box = "spox/ubuntu-arm" 
      scriptbox.vm.box_version = "1.0.0"
      scriptbox.vm.network "private_network", ip: "192.168.56.36"
      scriptbox.vm.hostname = "scriptbox"
      scriptbox.vm.provider "vmware_desktop" do |v|
        v.allowlist_verified = true
        v.ssh_info_public = true
        v.gui = true
    end
  end
    config.vm.define "web01" do |web01|    
    web01.vm.box = "bandit145/centos_stream9_arm"
    web01.vm.network "private_network", ip: "192.168.56.37"
    web01.vm.hostname = "web01"
    web01.vm.provider "vmware_desktop" do |v|
      v.allowlist_verified = true
      v.ssh_info_public = true
        v.gui = true
    end
  end
    config.vm.define "web02" do |web02|    
    web02.vm.box = "bandit145/centos_stream9_arm"
    web02.vm.network "private_network", ip: "192.168.56.38"
    web02.vm.hostname = "web02"
    web02.vm.provider "vmware_desktop" do |v|
      v.allowlist_verified = true
      v.ssh_info_public = true
        v.gui = true
    end
  end
end
